<a href="https://colab.research.google.com/github/dharveshkhan/me/blob/master/Copy_of_py_excercise5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Refer to the notes downloaded

In [ ]:
import numpy as np
array_1d=np.array([1,6,4,2,8,9,5,3,5])
print((array_1d[-1]))
print(array_1d[3:6:1])
print(array_1d[::-1])
print(type(array_1d[::-1]))
print(np.sum(array_1d)) # sum of the array

#do home work to calculate sum of hald the array, first half or sexond half and handle if its even or odd


5
[2 8 9]
[5 3 5 9 8 2 4 6 1]
<class 'numpy.ndarray'>
43
4.5


In [2]:
import numpy as np
array_2d=np.array([[1,2,3,4], [5,6,7,8], [4,7,9,2]])
print(array_2d)
print(array_2d.shape)
print(array_2d[0][0]) #indexing
print(array_2d[2][-1]) #indexing
print(array_2d[2,-1]) #indexing
#slicing
print(array_2d[1:-1,1:-1])


[[1 2 3 4]
 [5 6 7 8]
 [4 7 9 2]]
(3, 4)
1
2
2
[[6 7]]


In [7]:
import numpy as np
arr3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
print(arr3d.shape)
print(arr3d[1:,1:,1:])

(2, 3, 4)
[[[18 19 20]
  [22 23 24]]]


In [20]:
import numpy as np
ar= np.array(0)
ar.ndim
ar2 = np.array([[[ar]]])
ar2.ndim
ar2.shape

#number of backets no bracket (9) 0 dimension. [3] - 1 dimentions , [[9]] 2 dimentions and so on.

(1, 1, 1)

In [21]:
arr1d = np.array([ar])
arr1d.ndim

1

1d array is having 0d, 2d array is having 1d arrays and so on.

In [27]:
a3d = np.array([[[7,8,9,0,0], [7,8,9,0,0]],[[7,8,9,0,0], [7,8,9,0,0]]])
a3d.ndim
a3d.shape

(2, 2, 5)