<a href="https://colab.research.google.com/github/dharveshkhan/me/blob/master/myworkspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a="Dharvesh is a good boy"
print(a[-1::-1])

yob doog a si hsevrahD


In [ ]:
i=10.9999
j=20
print('my life is like a {:.3f} and {n}'.format(i,n=j))

my life is like a 11.000 and 20


In [ ]:
def findsum(a,b):
  c=a+b
  return c

findsum(10,20)

30

In [ ]:
class person:
  def __init__(self,name,age):
    self.name=name
    self.age=age

p1=person("Dharvesh",20)
i=1
j=1

for i in range(3):
  for j in range(3):
    x=person(i,j)
    print(x.name, x.age)


0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [ ]:
v1=1000
v2=1000
print(id(v1),id(v2))
print(v1 is v2)

133572785815600 133572785817072
False


In [ ]:
x=34

if x>50:
  print("a")
elif x>40 and x<50:
  print("b")
elif x>30 and x <40:
  print("c")
else:
  print("d")

c


In [ ]:
x=0

for x in range(11):
  x+=1
  print(x)
  y=x
print('harvesh is a rascal {}'.format(y))

1
2
3
4
5
6
7
8
9
10
11
harvesh is a rascal 11


In [ ]:
def dharvesh(x):
  y=x**3
  return(y)

print(dharvesh(990989777998))

973212154808807208801947908173335992


In [ ]:
for i in range(10):
  if i%2==0:
    continue
  print(i)

1
3
5
7
9


In [ ]:
x=10
while (x==10):
  x+=26
  print(x)


36


In [ ]:
a = [[1, 2], [3, 4]]
b = a.copy()

b[0][0] = 99

print("a:", a)
print("b:", b)


a: [[99, 2], [3, 4]]
b: [[99, 2], [3, 4]]


In [ ]:
a=[1,2,3,4]
b=a #here its deep copy.memory reference . but if i use .copy method it will not cleared the second list. shallow copy will stay at that point.
a.clear()
print(b)

[]


In [ ]:
a=[1,2,3,4]
b=[5,6,7,8]
d=['a']
d.append(a)
print(d)
a.clear()
print(d)

In [ ]:
{x: x**2 for x in range(1, 4)}

{1: 1, 2: 4, 3: 9}

In [ ]:
def greet(first, last):
    print(f"Hello {first} {last}")

greet(first="Dharvesh", last="Khan")   # Hello Dharvesh Khan
greet(last="Khan", first="Dharvesh")

Hello Dharvesh Khan
Hello Dharvesh Khan


In [ ]:
try:
  x=5/0
except Exception as f:
  print("error", f)

error division by zero


In [ ]:
a=(1,2,3,4,5)
#print(dir(a))
a.count(2)

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']


1

In [ ]:
a=set()
a={1,2,3}
print((a))
a.update([6,7,8])
a.remove(6)
a.update((6,8))
b=a.copy()
a.clear()
print(a)
print(b)

{1, 2, 3}
set()
{1, 2, 3, 6, 7, 8}


In [ ]:
myd={"a": "dharvesh", "b": 23232}
print(myd)
print(myd.keys())
print(myd["a"])

{'a': 'dharvesh', 'b': 23232}
dict_keys(['a', 'b'])
dharvesh


In [ ]:
{x:x**2 for x in range(1,6) }

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [ ]:
{x:x**3 for x in range(1,11) if x%2==0}

{2: 8, 4: 64, 6: 216, 8: 512, 10: 1000}

In [ ]:
words = ["apple", "banana", "cherry"]
{word:len(word) for word in words}

{'apple': 5, 'banana': 6, 'cherry': 6}

In [ ]:

nums = {"a": 10, "b": 15, "c": 20, "d": 25}

def gret(x):
  if x>15:
    print(x)
    return(x)



for num in nums.values():
  gret(num)
  #print(num)


20
25


In [ ]:
nums = {"a": 10, "b": 15, "c": 20, "d": 25}

dc = {x:y for x,y in nums.items() if y >15}
print (dc)

{'c': 20, 'd': 25}


In [ ]:
fruits = ["apple", "banana", "cherry"]
fr= {"fruitname":y.upper() for y in fruits}
print(fr)

{'fruitname': 'CHERRY'}


In [ ]:
def eve(n):
  if n%2==0:
    return n*2

print(list(map(eve,range(20))))

[0, None, 4, None, 8, None, 12, None, 16, None, 20, None, 24, None, 28, None, 32, None, 36, None]


In [ ]:
def gr(*n):
  for i in n:
   print("hi good morning{}".format(i))
gr("dharvesh","khan")

hi good morningdharvesh
hi good morningkhan


In [ ]:
def total(*numbers):
    print(numbers)        # tuple
    return sum(numbers)

print(total(1, 2, 3, 4))  # (1, 2, 3, 4) → 10

(1, 2, 3, 4)
10


In [ ]:
def arb(**n):
  print(n)
  for i in n.values():
    print(i)
d={"a": 123, "v":333}
arb(**d)

{'a': 123, 'v': 333}
123
333


In [ ]:
s=lambda x: (
    x*2,
    x**3,
    x+3)
print(s(4))

(8, 64, 7)


In [ ]:
nums = [1, 2, 3, 4, 5]
u=list(map((lambda x: x**2),nums))
print(u)


[1, 4, 9, 16, 25]


In [ ]:
nums = [10, 15, 20, 25, 30, 35, 40]
nums = list(filter((lambda x: x%2==0), nums))
print(nums)


[10, 20, 30, 40]


In [ ]:
ums = [1, 2, 3, 4, 5, 6, 7, 8, 9]
ums=list(map(lambda y: y*2, filter(lambda x: x%2==1, ums)))
print(ums)

[2, 6, 10, 14, 18]


In [ ]:
import numpy as np
a=np.array([[[[9]]]])
print(a)
print(a.ndim)
print(a.shape)
print(type(a))

[[[[9]]]]
4
(1, 1, 1, 1)
<class 'numpy.ndarray'>


In [ ]:
l1=[1,2,3,4,5]
print(l1)
a=np.array(l1)
print(a)
print(id(a[2]))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
136243147713840


In [ ]:
#Create 0D, 1D, 2D, 3D
#Create a 0D array:
import numpy as np
print('---------0D array--------------')
arr = np.array(42) # Single numerical value when converted to a numpy array, gives 0D array.
print(arr)

#Create 1D array
print('---------1D array--------------')
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Create 2D array
print('---------2D array--------------')
arr2 = np.array([[1, 2, 3], [4, 5, 6], [4, 5, 6], [4, 5, 6], [4, 5, 6], [4, 5, 6], [4, 5, 6]]) # Combination of multiple 1D array gives 2D array
print(arr2)

#Create a 3D array
print('---------3D array--------------')
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])
# print(arr3)
print(arr3[-1])

---------0D array--------------
42
---------1D array--------------
[1 2 3 4 5]
---------2D array--------------
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
---------3D array--------------
[[1 2 3]
 [4 5 6]]


In [ ]:
x= np.array(['Hello', 'Hello'])
y= np.array(['WelcomeHello', 'Learners'])
result = np.char.add(x,y)
print(result)
result1 = x+y
print(result1)
result2 = np.char.add(x,y)
print(result2)
result3=np.char.replace(result2, 'Hello', 'Meow')
print(result3)

['HelloWelcomeHello' 'HelloLearners']
['HelloWelcomeHello' 'HelloLearners']
['HelloWelcomeHello' 'HelloLearners']
['MeowWelcomeMeow' 'MeowLearners']


In [ ]:
#Create a 1d, 2d and 3d array
arr1D = np.array([1,2,3,4,5,6])
arr2D = np.array([[1,2,3,4,5,6],[6,7,5,4,5,0]])
arr3D = np.array([[[1,2,3,4,5,6],[6,7,5,4,5,0]], [[1,2,4,4,5,6],[6,7,5,4,5,9]]])
arr4D = np.array([[[1,2,3,4,5,6],[6,7,5,4,5,0]], [[1,2,4,4,5,6],[6,7,5,4,5,9]]])
#print('----------1D array------------')
#print(arr1D)
#print('----------2D array------------')
#print(arr2D)
#print('----------3D array------------')
#print(arr3D)

#print(arr2D[:1:])
arr3D+arr4D

array([[[ 2,  4,  6,  8, 10, 12],
        [12, 14, 10,  8, 10,  0]],

       [[ 2,  4,  8,  8, 10, 12],
        [12, 14, 10,  8, 10, 18]]])

In [ ]:
x= np.array([[1,2,3,4,5],[3,4,5,56,6]])
print(id(x[0]))
print(id(x[1]))

136243144793936
136243144793936


In [ ]:
a= np.array([1,2,3,4,5])
b= np.array([2]) # Broadcasting in Numpy. [1,1,1,1,1]
np.modulo(a,b)

AttributeError: module 'numpy' has no attribute 'modulo'

In [ ]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,100])
np.median(array1)

np.float64(6.0)

In [ ]:
import numpy as np
x= range(1,300)
print(x)
list1=list(x)
print(list1)
np.percentile(list1, 25)

range(1, 300)
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219

np.float64(75.5)

In [26]:
A= [15, 25, 35, 45, 55]
B= [5, 10, 15, 20, 25]
C= [12, 22, 32, 42, 52, 62, 72, 82, 92, 102]
X= ['Hello', 'Data', 'Science', 'Class', 'Learners']
Y= ['World', 'Analysis', 'is', 'Fun', '2023']
a = np.array(A)
b=np.array(B)
c=np.array(C)
x=np.array(X)
y=np.array(Y)
print(np.multiply(a,b))


[  75  250  525  900 1375]


In [ ]:

print(np.random.randint(1,1980,354))

[ 835   44  998   45 1784  261 1160  845  546  556 1361 1010  458 1912
  411 1117  890  218  774  204 1882  693 1919  799 1310 1726  871 1525
  533 1577  258  941 1470 1543  802 1091 1117  381 1681  124 1008  314
 1580 1052  649  993   40 1512 1670  920   27  912  577  391 1803  150
  940 1287  312 1727 1508  343  400 1674 1687 1105 1698 1536   51  281
 1487  384  290 1701  979  489 1204 1515 1554 1566 1797 1757  648 1317
  934  348 1694  956 1813  431 1182 1259  538  324 1011 1501  543  837
  828 1036 1926  258  108  158   91  931   61  633 1905 1095  356 1811
 1973  672 1505  922 1917  210 1510  124  219  770 1309 1589   99  681
 1842   50  823  311 1144   50  381 1130 1446  292 1313 1963  146 1738
  977 1400  650  755  153  330  439  969   27 1132  990  787  733 1586
   35 1120 1613  452  188   88 1950  487 1487  760   74  446 1536 1734
  808  430 1604 1337 1273  374 1870 1197  624 1863   38 1935 1282 1357
  424  668 1575 1538  407 1780 1415 1388 1276 1151   11  468 1612  750
  427 

In [21]:
q=np.random.randint(1,999,(3,4,5))
q


array([[[113, 806,  34, 877, 322],
        [597,  97, 634, 676, 560],
        [250, 603, 966, 887, 871],
        [300,  79, 521, 963, 170]],

       [[434, 283, 776, 694, 379],
        [273, 843, 531, 558, 923],
        [966, 983, 978, 304, 248],
        [333, 312, 955, 320, 807]],

       [[564, 953, 632, 963, 270],
        [ 96, 959, 148, 933,  60],
        [625, 910, 887,  56, 226],
        [172, 598, 928, 432, 220]]])

In [24]:
print(q[1:,3:,3:])

[[[320 807]]

 [[432 220]]]


In [27]:
x=np.array([1,2,3,4,5])
y=np.array([3,4,5,6,7])
np.greater(x,y)

array([False, False, False, False, False])

In [30]:
arr2d = np.array(np.random.randint(1,10, (2,5)))
arr2d

array([[1, 2, 3, 8, 2],
       [8, 7, 2, 2, 1]])

In [32]:
ar =arr2d[::-1]
ar

array([[8, 7, 2, 2, 1],
       [1, 2, 3, 8, 2]])

In [33]:
arr3d = np.array(np.random.randint(1,10,(2,3,4)))
arr3d

array([[[2, 6, 6, 3],
        [7, 2, 2, 7],
        [2, 9, 7, 6]],

       [[8, 7, 3, 5],
        [5, 7, 5, 7],
        [1, 9, 3, 9]]])

In [34]:
arr3d[::-1][::-1][::-1]

array([[[8, 7, 3, 5],
        [5, 7, 5, 7],
        [1, 9, 3, 9]],

       [[2, 6, 6, 3],
        [7, 2, 2, 7],
        [2, 9, 7, 6]]])

In [56]:
arr1D= np.array([1,2,3,4,5,6,7,8,9,10]) # By default the 1D array is 10,1 shape not 1,10.

x=arr1D.reshape(5,1,2)
print(x)
print(x.shape)
t=x.flatten()
print(t)



[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]]
(5, 1, 2)
[ 1  2  3  4  5  6  7  8  9 10]


In [58]:
arr1D = np.array(range(1,24))
print(arr1D)
arr1D.reshape(1,1,23)
arr1D.dtype

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


dtype('int64')

In [59]:
q=list(range(1,10,2))
print(type(q))

<class 'list'>


In [61]:
np.zeros(27).reshape(3,1,1,3,3)

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [63]:
np.linspace(0,3,4)

array([0., 1., 2., 3.])

In [66]:
print(np.arange(10,0))

[]


In [67]:
np.eye(127)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [68]:
arr2d = np.arange(1,13).reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [74]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.sum(arr)

np.int64(55)

In [86]:

arr_x = np.array([[1,2,3,4], [5,6,7,8]])
arr_y = np.array([[21,22,23,24], [25,26,27,28]])
print(arr_x.shape)
arr_z = np.concatenate((arr_x, arr_y), axis=0)
print(arr_z)
print(arr_z.shape)

(2, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [21 22 23 24]
 [25 26 27 28]]
(4, 4)


In [96]:
import pandas as pd
countries=['India', 'France', 'England','India']
capitals = ['New Delhi','Paris',' London','New Delhi']
v=pd.Series(capitals, index=countries, name='capitals')
v[0]


/tmp/ipython-input-2160826839.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  v[0]


'New Delhi'

In [100]:
#Creating pandas Series from a Dictionary
dicts = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70, 'h':80, 'a':90} # Dictionary dont support duplicate keys.
my=pd.Series(dicts, name="meow")# When converting a dictionary to a Series, the dict.key is set as index and dict.value is set as value of the Series.
print(my[-1: int(len(my)/2):-1])

h    80
g    70
f    60
Name: meow, dtype: int64


In [107]:
fruits = ['Apple','Banana','Mango','Grapes']
pd.DataFrame(fruits, columns=['fruits']) # Columns is used to set the column name

fruits
0   Apple
1  Banana
2   Mango
3  Grapes

In [109]:
people = [['Rick', 60, 'O+'], ['Monty',10,'O+'], ['summer', 45, 'A+'], ['Beth', 18, 'B+']]
df = pd.DataFrame(people, columns=['Name', 'Age', 'Blood Group'])
print(df)

     Name  Age Blood Group
0    Rick   60          O+
1   Monty   10          O+
2  summer   45          A+
3    Beth   18          B+


In [111]:
#Create DataFrame from Dictionary
people = {'Name':['Rick', 'Monty', 'Summer', 'Rick'], 'Age':[60, 10, 45, 18], 'Blood Group':['O+', 'O+', 'A+', 'B+']}
people_df = pd.DataFrame(people)
people_df.set_index('Name' , inplace=True)
people_df

Age Blood Group
Name                   
Rick     60          O+
Monty    10          O+
Summer   45          A+
Rick     18          B+

In [120]:
g=([30, 33],[30, 33],[30, 33])
pd.DataFrame(g, columns=['Name', 'Age'])

Name  Age
0    30   33
1    30   33
2    30   33